### PR TITLE
Added synchronization flow diagram.

### PR DESCRIPTION
**Pull request by n1k0**
r=? @ametaireau @Natim @leplatrem

### CODE REVIEW

**Comment by Natim** [comment]
I don't know if it is out of this PR scope but we should add something about syncing from a flushed server. (collection timestamp mismatch with no changes)

**Comment by n1k0** [comment]
There's issue #44 opened about that.

**Comment by ametaireau** [comment]
I <3 diagrams. Thanks for doing this.?

**Comment by leplatrem** [comment]
Neat ! 
I couldn't find any nit :) 

Maybe, you could commit the original file along (even if from proprietary software), so that anyone can contribute changes to the diagram eventually

**Comment by n1k0** [comment]
> Maybe, you could commit the original file along

Updated the patch with the [draw.io](https://draw.io/) XML source.

**Pull request merged**
