### PR TITLE
Refs #40 - Added checks for supported protocol version.

### PR DESCRIPTION
**Pull request by n1k0**
WiP, do not merge yet.

- [x] Define and export a `SUPPORTED_PROTOCOL_VERSION` constant defining the protocol version the client actually supports; eg. `export const SUPPORTED_PROTOCOL_VERSION = "v1"`;
- [x] Ensure the version passed in the `remote` property matches that constant value; raise on mismatch with an appropriate error message;
- [x] Request server endpoints using that `SUPPORTED_PROTOCOL_VERSION` value;
- [x] On each HTTP request made to the Kinto server, check for `404` status code with an `errno` set to `VERSION_NOT_AVAILABLE` in the response; reject with an explicit message in such case;
- [x] Update docs;
- [x] Update dist files.

### CODE REVIEW

**Comment by n1k0** [comment]
This is now ready for review I guess. r=? @leplatrem @ametaireau @Natim

**Comment by n1k0** [comment]
Don't merge yet, there's an issue with the demo.

**Comment by elemoine** [comment]
> Don't merge yet, there's an issue with the demo.

I've always thought that it's better to have the author merge his PRs. Just saying… Nothing to act on really :)

**Comment by n1k0** [comment]
True that.

So this is currently blocked by https://github.com/mozilla-services/kinto/issues/126.

**Comment by ametaireau** [comment]
LGTM.

**Comment by n1k0** [comment]
> So this is currently blocked by mozilla-services/kinto#126.

Actually, this is not blocked by this issue, only fixing the demo is, thought it's not related to this patch. Gonna land this.

**Pull request merged**
