### PR TITLE
Fixes #57 - Better HTTP error handling.

### LINKED ISSUE #57: Refactor generic HTTP error handling.
Current situation is a mess, eg duplicated code and most importantly, we're losing stack traces when throwing new errors instead of propagating them.

### PR DESCRIPTION
**Pull request by n1k0**
Refs #57. This is quite an heavy refactoring though I think it greatly improves the current situation.

r=? @leplatrem @Natim @ametaireau

### CODE REVIEW

**Comment by n1k0** [comment]
screen shot 2015-07-10 at 19 23 35

:(

**Comment by n1k0** [comment]
I quit.

**Comment by n1k0** [comment]
Hosanah au plus haut des cieux. r=? @leplatrem @Natim @ametaireau

**Comment by leplatrem** [comment]
r+

5vdqvnd

**Pull request merged**
