### PR TITLE
Rename project to kinto.js

### PR DESCRIPTION
**Pull request by Natim**
There's been some confusion around the scope of Cliquetis, which in its current form is much more of a Kinto client than a Cliquet one. We should rename the project to reflect the situation and avoid creating more confusion.

### CODE REVIEW

**Comment by Natim** [comment]
I don't have necessary rights to create kinto.js.readthedocs.org and I don't even know if it is possible to do so or if we should use kinto-js.readthedocs.org instead.

**Comment by n1k0** [comment]
r+, as I *think* the coverage badge will show up once a report using the new project repo url is generated.

**Comment by Natim** [comment]
The badge actually works: https://coveralls.io/repos/mozilla-services/kinto.js/badge.svg?branch=master
But the image cached by github is not the right one yet.

**Pull request merged**
