### PR TITLE
Kinto setup script.

### PR DESCRIPTION
**Pull request by n1k0**
Just for fun, let's see how travis handles this.

### CODE REVIEW

**Comment by n1k0** [comment]
Last build failure is interesting:

```
.venv/bin/cliquet --ini config/kinto.ini migrate

Traceback (most recent call last):

  File ".venv/bin/cliquet", line 9, in <module>

    load_entry_point('cliquet==2.1.0.dev0', 'console_scripts', 'cliquet')()

  File "/var/tmp/kinto/.venv/lib/python2.7/site-packages/cliquet/scripts/cliquet.py", line 48, in main

    env = bootstrap(args.ini_file)

  File "/var/tmp/kinto/.venv/lib/python2.7/site-packages/pyramid-1.6a1-py2.7.egg/pyramid/paster.py", line 131, in bootstrap

    app = get_app(config_uri, options=options)

  File "/var/tmp/kinto/.venv/lib/python2.7/site-packages/pyramid-1.6a1-py2.7.egg/pyramid/paster.py", line 31, in get_app

    global_conf=options)

  File "/var/tmp/kinto/.venv/lib/python2.7/site-packages/PasteDeploy-1.5.2-py2.7.egg/paste/deploy/loadwsgi.py", line 247, in loadapp

    return loadobj(APP, uri, name=name, **kw)

  File "/var/tmp/kinto/.venv/lib/python2.7/site-packages/PasteDeploy-1.5.2-py2.7.egg/paste/deploy/loadwsgi.py", line 271, in loadobj

    global_conf=global_conf)

  File "/var/tmp/kinto/.venv/lib/python2.7/site-packages/PasteDeploy-1.5.2-py2.7.egg/paste/deploy/loadwsgi.py", line 296, in loadcontext

    global_conf=global_conf)

  File "/var/tmp/kinto/.venv/lib/python2.7/site-packages/PasteDeploy-1.5.2-py2.7.egg/paste/deploy/loadwsgi.py", line 320, in _loadconfig

    return loader.get_context(object_type, name, global_conf)

  File "/var/tmp/kinto/.venv/lib/python2.7/site-packages/PasteDeploy-1.5.2-py2.7.egg/paste/deploy/loadwsgi.py", line 454, in get_context

    section)

  File "/var/tmp/kinto/.venv/lib/python2.7/site-packages/PasteDeploy-1.5.2-py2.7.egg/paste/deploy/loadwsgi.py", line 476, in _context_from_use

    object_type, name=use, global_conf=global_conf)

  File "/var/tmp/kinto/.venv/lib/python2.7/site-packages/PasteDeploy-1.5.2-py2.7.egg/paste/deploy/loadwsgi.py", line 406, in get_context

    global_conf=global_conf)

  File "/var/tmp/kinto/.venv/lib/python2.7/site-packages/PasteDeploy-1.5.2-py2.7.egg/paste/deploy/loadwsgi.py", line 296, in loadcontext

    global_conf=global_conf)

  File "/var/tmp/kinto/.venv/lib/python2.7/site-packages/PasteDeploy-1.5.2-py2.7.egg/paste/deploy/loadwsgi.py", line 328, in _loadegg

    return loader.get_context(object_type, name, global_conf)

  File "/var/tmp/kinto/.venv/lib/python2.7/site-packages/PasteDeploy-1.5.2-py2.7.egg/paste/deploy/loadwsgi.py", line 620, in get_context

    object_type, name=name)

  File "/var/tmp/kinto/.venv/lib/python2.7/site-packages/PasteDeploy-1.5.2-py2.7.egg/paste/deploy/loadwsgi.py", line 640, in find_egg_entry_point

    pkg_resources.require(self.spec)

  File "/var/tmp/kinto/.venv/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 952, in require

    needed = self.resolve(parse_requirements(requirements))

  File "/var/tmp/kinto/.venv/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 844, in resolve

    raise VersionConflict(dist, req).with_context(dependent_req)

pkg_resources.ContextualVersionConflict: (cliquet 2.1.0.dev0 (/var/tmp/kinto/.venv/lib/python2.7/site-packages), Requirement.parse('cliquet[postgresql,monitoring]<2.0'), set(['kinto']))
```

Ideas? @leplatrem @ametaireau @Natim

**Comment by Natim** [comment]
cd cliquet
    pip install -e .

**Comment by n1k0** [comment]
Hmm need to resolve cliquet's path on travis envoronment, sounds bad. @Natim any reason e have to do this? Why isn't it done by default?

**Comment by Natim** [comment]
I think it is because you deployed a previous version of cliquet and now the dependencies are out of date.

If you install it using pip install kinto you won't have this problem.

**Comment by Natim** [comment]
Oh I didn't see it was on travis. Then I guess the < 2.0 is not accurate anymore on kinto.

**Comment by Natim** [comment]
According to https://github.com/mozilla-services/kinto/blob/master/setup.py#L18 it should be > 2.0 and not < 2.0

**Comment by Natim** [comment]
Ok for kinto 0.2.2 it should be < 2.0 https://github.com/mozilla-services/kinto/blob/0.2.2/setup.py#L18

 don't understand why cliquet 2.1.0.dev is installed then.

**Comment by Natim** [comment]
Fixed here : https://github.com/mozilla-services/kinto/tree/0.2.x

You can use the 0.2.x branch instead of the 0.2.2 commit for this.

**Comment by n1k0** [comment]
So the setup is validated, I think we can safely merge this, and start writing more tests. r=? @Natim @leplatrem @ametaireau

**Pull request merged**
